backend:
  name: github
  repo: JosemyDuarte/josemyduarte.github.io
  branch: release
media_folder: 'assets/img'
collections:
  - name: "blog" 
    label: "Posts" 
    label_singular: "Post"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: 'YYYY-MM-DD', time_format: false}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Share Image", name: "share-img", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
